### ISSUE TITLE
suggest patch on branch master

### ISSUE THREAD

**Issue by taufiqsumadi** [egin10/belajar_web#5]
gin kalo dilihat [network](https://github.com/egin10/belajar_web/network) semua peubahan yang kamu lakuin kamu buat fork sendiri ya, kenapa enggak di master aja gin? kan kamu ownernya karena semua perubahan yang kamu lakuin ga masuk ke branch master, atau kamu marge ke master aja deh

thank you @egin10

**Comment by egin10** [comment]
tunggu selesai semua baru merge ke master, itu buat ngajarin mereka untuk push kerjaan mereka ke branch masing-masing

thank you @taufiqsumadi
